// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package modelo

import (
	"database/sql"
)

type Analise struct {
	ID           int32          `json:"id"`
	ItenID       int32          `json:"iten_id"`
	FornecedorID int32          `json:"fornecedor_id"`
	Atende       sql.NullBool   `json:"atende"`
	Obs          sql.NullString `json:"obs"`
	Analista     sql.NullString `json:"analista"`
}

type Componente struct {
	ID       int32  `json:"id"`
	Nome     string `json:"nome"`
	ModeloID int32  `json:"modelo_id"`
}

type Equipamento struct {
	ID       int32  `json:"id"`
	Nome     string `json:"nome"`
	TipoID   int32  `json:"tipo_id"`
	ModeloID int32  `json:"modelo_id"`
}

type Fornecedor struct {
	ID   int32  `json:"id"`
	Nome string `json:"nome"`
}

type Iten struct {
	ID            int32 `json:"id"`
	EquipamentoID int32 `json:"equipamento_id"`
	PregaoNumero  int32 `json:"pregao_numero"`
	PregaoAno     int32 `json:"pregao_ano"`
	SolicitanteID int32 `json:"solicitante_id"`
}

type Marca struct {
	ID   int32  `json:"id"`
	Nome string `json:"nome"`
}

type Modelo struct {
	ID      int32  `json:"id"`
	Nome    string `json:"nome"`
	MarcaID int32  `json:"marca_id"`
}

type Peca struct {
	EquipamentoID int32 `json:"equipamento_id"`
	ComponenteID  int32 `json:"componente_id"`
}

type Pregao struct {
	Username   string       `json:"username"`
	CreateTime sql.NullTime `json:"create_time"`
	UpdateTime sql.NullTime `json:"update_time"`
	Numero     int32        `json:"numero"`
	Ano        int32        `json:"ano"`
}

type Solicitante struct {
	ID   int32  `json:"id"`
	Nome string `json:"nome"`
}

type Tipo struct {
	ID   int32  `json:"id"`
	Nome string `json:"nome"`
}
