// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package modelo

import (
	"context"
)

type Querier interface {
	CreateFornecedor(ctx context.Context, nome string) (Fornecedor, error)
	CreateMarca(ctx context.Context, nome string) (Marca, error)
	CreateModelo(ctx context.Context, arg CreateModeloParams) (Modelo, error)
	DeleteFornecedor(ctx context.Context, id int32) error
	DeleteMarca(ctx context.Context, id int32) error
	DeleteModelo(ctx context.Context, id int32) error
	FindFornecedorByName(ctx context.Context, nome string) ([]Fornecedor, error)
	FindMarcaByName(ctx context.Context, arg FindMarcaByNameParams) ([]Marca, error)
	FindMarcasByName(ctx context.Context, nome string) ([]Marca, error)
	FindModelosByMarca(ctx context.Context, arg FindModelosByMarcaParams) ([]Modelo, error)
	FindModelosByName(ctx context.Context, arg FindModelosByNameParams) ([]Modelo, error)
	GetFornecedorById(ctx context.Context, id int32) (Fornecedor, error)
	GetFornecedorByName(ctx context.Context, nome string) (Fornecedor, error)
	GetMarcaById(ctx context.Context, id int32) (Marca, error)
	GetMarcaByName(ctx context.Context, nome string) (Marca, error)
	GetModeloById(ctx context.Context, id int32) (Modelo, error)
	GetModeloByName(ctx context.Context, nome string) (Modelo, error)
	ListFornecedores(ctx context.Context) ([]Fornecedor, error)
	ListMarcas(ctx context.Context) ([]Marca, error)
	ListModelos(ctx context.Context) ([]Modelo, error)
	UpdateFornecedor(ctx context.Context, arg UpdateFornecedorParams) (Fornecedor, error)
	UpdateMarca(ctx context.Context, arg UpdateMarcaParams) (Marca, error)
	UpdateModelo(ctx context.Context, arg UpdateModeloParams) (Modelo, error)
}

var _ Querier = (*Queries)(nil)
