// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package database

import (
	"context"
)

type Querier interface {
	CreateMarca(ctx context.Context) (int64, error)
	DeleteMarca(ctx context.Context) error
	FindMarcaByName(ctx context.Context) ([]InfraMarca, error)
	GetMarcaById(ctx context.Context) (InfraMarca, error)
	GetMarcaByName(ctx context.Context) (InfraMarca, error)
	ListMarcas(ctx context.Context) ([]InfraMarca, error)
	UpdateMarca(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
