#criar e rodar um container: docker compose up -d
#iniciar todos serviços:docker compose start
#parar todos serviços:docker compose stop
#acesso ao container: docker exec -it nomedocontainer bash|sh


version: '3'
services:

  db:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: infra
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pmscs.123
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "30432:5432"
    expose:
      - 5432
      - 30432

    networks:
      - dbnet
    #logging:
    #  driver: syslog
    #  options:
    #    syslog-address: "tcp://192.168.0.42:123"

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    restart: always
    ports: 
      - "8088:8080"
    networks:
      - dbnet

volumes:
  pgdata:
    external: true

networks:
  dbnet:
    name: dbnet
    driver: bridge
